apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    isDefault: true
    jsonData:
      serviceMap:
        datasourceUid: 'mimir'

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki

  - name: Mimir
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    uid: mimir 